App/views/expert.py
from datetime import datetime
from flask import Blueprint, render_template, flash, redirect, url_for
from flask_login import login_user, logout_user, login_required, current_user
from App.forms import Register, Login  # 导入表单注册类
from App.models import User  # User 模型类

expert = Blueprint('expert', __name__)

"""
# 注册步骤
1. 创建模型类
2. 加载flask-migrate扩展库（迁移）
3. 在视图函数中导入模型类
4. 验证用户名是否存在
5. 获取模板前台传递过来的数据
6. 存储
7. 明文密码变成密文密码（加密存储）
8. 消息闪现（注册成功，前去激活...）
"""


@expert.route('/register_ex/', methods=['GET', 'POST'])
def register():
    # 实例化注册表单类
    form = Register()
    # 实例化存储注册表单数据
    e = User()
    if form.validate_on_submit():
        e.username = form.username.data
        e.password = form.userpass.data
        e.email = form.email.data
        e.registerTime = datetime.now()
        e.status = '专家'
        if e.save():
            flash('注册成功，已为您跳转到登录页面...')
        return redirect(url_for('expert.login'))
    return render_template('expert/register.html', form=form)


@expert.route('/login_ex/', methods=['GET', 'POST'])
def login():
    form = Login()
    if form.validate_on_submit():
        u = User.query.filter(User.username == form.username.data).first()
        if not u:
            flash('请输入正确的用户名')
        elif not u.check_password(form.userpass.data):
            flash('密码有误，请输入正确的密码...')
        elif u.status != '专家':
            flash('您不是专家哦~')
        else:
            # 修改登录时间
            u.lastLogin = datetime.now()
            u.save()
            login_user(u, remember=form.remember.data)  # 使用第三方扩展库处理登录状态的维持
            return redirect(url_for('expert.main_page'))
    return render_template('expert/login.html', form=form)


# 专家主页面
@expert.route('/main_page_ex/')
@login_required
def main_page():
    if current_user.status == '专家':  # 当前用户是专家，才会渲染下面的模板，否则渲染nocan.html
        u = current_user
        return render_template('main/main_expert.html', user=u)
    else:
        return render_template('common/nocan.html', u=current_user.username)


# 退出登录
@expert.route('/logout_ex/')
def logout():
    logout_user()  # 清除当前用户所有数据
    return redirect(url_for('main.index'))

App/templates/expert/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>在线投稿与稿件管理系统-专家页面</title>
    <link rel="stylesheet" href="../../static/dist/css/bootstrap.css">
    <script src="../../static/js/jquery-1.12.4.js"></script>
    <style>
        body {
            background: url("../../static/img/bj02.jpg") fixed center/100% 100%;
        }

        .ff {
            width: 1150px;
            height: 450px;
            position: relative;
            padding-left: 50px;
            margin: 150px auto 0;
        }

        .father {
            width: 320px;
            border: 1px solid #888;
            border-radius: 4px;
            position: absolute;
            right: 0;
            background-color: rgba(180, 180, 200, 0.7);
        }

        .son1, .son2, .son3 {
            width: 100%;
        }

        .son1 {
            height: 100px;
            padding-top: 20px;
        }

        .son1 p {
            font-size: 42px;
            font-weight: 700;
            font-family: "楷体";
            line-height: 100px;
            text-align: center;
            color: #1cf;
        }

        .son2 {
            height: 260px;
            padding: 20px 50px 0;
            color: #eee;
        }

        .son3 {
            height: 80px;
            padding: 0 50px;
        }

        .son3 a {
            color: #fc1;
            font-style: italic;
            font-size: 13px;
            margin-left: 80px;
            line-height: 50px;
        }

        .my_title {
            width: 600px;
            position: absolute;
            top: 50px;
        }

        .my_title h1 {
            font-size: 60px;
            line-height: 100px;
            color: #1cf;
        }

        .my_title p {
            font-size: 30px;
            line-height: 50px;
            text-indent: 50px;
            color: #1cf;
        }
    </style>
</head>
<body>
<div class="info">
    {% for info in get_flashed_messages() %}
        <div class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                    aria-hidden="true">&times;</span>
            </button>
            {{ info }}
        </div>
    {% endfor %}
</div>
<div class="ff">

    <div class="my_title">
        <h1>在线投稿与稿件处理</h1>
        <p>专家登录页面</p>
    </div>
    <div class="father">
        <div class="son1">
            <p>欢迎登录</p>
        </div>
        <div class="son2">
            {% from 'bootstrap/wtf.html' import quick_form %}
            {{ quick_form(form) }}

        </div>
        <div class="son3">
            <a href="{{ url_for('expert.register') }}">没有账户？点我注册</a>
        </div>
    </div>
</div>

<script src="../../static/dist/js/bootstrap.js"></script>
</body>
</html>

App/templates/expert/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>在线投稿与稿件管理系统-专家界面</title>
    <link rel="stylesheet" href="../../static/dist/css/bootstrap.css">
    <script src="../../static/js/jquery-1.12.4.js"></script>
    <style>
        body {
            background: url("../../static/img/bj02.jpg") fixed center/100% 100%;
        }

        .ff {
            width: 1150px;
            height: 550px;
            position: relative;
            padding-left: 50px;
            margin: 100px auto 0;
        }

        .father {
            width: 350px;
            border: 1px solid #888;
            border-radius: 4px;
            position: absolute;
            right: 0;
            background-color: rgba(180, 180, 200, 0.7);
        }

        .son1, .son2, .son3 {
            width: 100%;
        }

        .son1 {
            height: 100px;
            padding-top: 20px;
        }

        .son1 p {
            font-size: 42px;
            font-weight: 700;
            font-family: "楷体";
            line-height: 100px;
            text-align: center;
            color: #f92;
        }

        .son2 {
            height: 350px;
            padding: 20px 50px 0;
            color: #eee;
        }

        .son3 {
            height: 80px;
            padding: 0 50px;
        }

        .son2 a {
            color: #fc1;
            font-style: italic;
            font-size: 13px;
            margin-left: 110px;
            line-height: 60px;
        }

        .my_title {
            width: 600px;
            position: absolute;
            top: 100px;
        }

        .my_title h1 {
            font-size: 60px;
            line-height: 100px;
            color: #f92;
        }

        .my_title p {
            font-size: 30px;
            line-height: 50px;
            text-indent: 320px;
            color: #f92;
        }
    </style>
</head>
<body>
<div class="info">
    {% for info in get_flashed_messages() %}
        <div class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                    aria-hidden="true">&times;</span>
            </button>
            {{ info }}
        </div>
    {% endfor %}
</div>
<div class="ff">
    <div class="my_title">
        <h1>在线投稿与稿件处理</h1>
        <p>专家注册页面</p>
    </div>
    <div class="father">
        <div class="son1">
            <p>欢迎注册</p>
        </div>
        <div class="son2">
            {% from 'bootstrap/wtf.html' import quick_form %}
            {{ quick_form(form) }}
            <a href="{{ url_for('expert.login') }}">已有账户？点我登录</a>
        </div>
        <div class="son3"></div>
    </div>
</div>

<script src="../../static/dist/js/bootstrap.js"></script>
<script src="../../static/dist/js/npm.js"></script>
</body>
</html>