App/views/admin.py
from datetime import datetime
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_user, logout_user, login_required, current_user
from App.models import User  # User 模型类

admin = Blueprint('admin', __name__)

"""
# 注册步骤
1. 创建模型类
2. 加载flask-migrate扩展库（迁移）
3. 在视图函数中导入模型类
4. 验证用户名是否存在
5. 获取模板前台传递过来的数据
6. 存储
7. 明文密码变成密文密码（加密存储）
8. 消息闪现（注册成功）
"""


# 在最开始没有管理员时，使用本方法创建一个至高无上的管理员
@admin.route('/root/', methods=['GET', 'POST'])
def root():
    # 创建管理员表单对象
    ad = User()
    if User.query.filter(User.username == 'root').first():
        # 管理员已经存在
        num = 1
    else:
        # 给一个最开始的管理员、权限全开
        ad.username = 'root'
        ad.password = '123456'
        ad.email = '1234567898@qq.com'
        ad.registerTime = datetime.now()
        ad.status = '管理员'
        ad.leaderId = 0
        ad.permissions = 31
        # flash('测试')
        if ad.save():
            # 注册成功
            num = 2
        else:
            # 注册失败
            num = 3
    return render_template('admin/root_register.html', num=num)


@admin.route('/register_ad/', methods=['GET', 'POST'])
@login_required
def register():
    if current_user.status == '管理员':  # 当前用户是管理员，才会渲染下面的模板，否则渲染nocan.html
        # 创建管理员表单对象
        ad = User()
        if request.method == 'POST':
            if User.query.filter(User.username == request.form.get('adname')).first():
                flash('用户名已存在')
            if User.query.filter(User.email == request.form.get('email')).first():
                flash('邮箱已存在')
            if request.form.get('passwd') != request.form.get('repass'):
                flash('两次输入的密码不一样，请重新输入...')
            else:
                ad.username = request.form.get('adname')
                ad.password = request.form.get('passwd')
                ad.email = request.form.get('email')
                ad.registerTime = datetime.now()
                ad.status = '管理员'

                ad.leaderId = current_user.id
                num = 0  # 权限初始值
                if request.form.get('pe1'):
                    num += int(request.form.get('pe1'))
                if request.form.get('pe2'):
                    num += int(request.form.get('pe2'))
                if request.form.get('pe4'):
                    num += int(request.form.get('pe4'))
                if request.form.get('pe8'):
                    num += int(request.form.get('pe8'))
                ad.permissions = num
                if ad.save():
                    flash('注册成功...')
                else:
                    flash('注册失败...')
        if current_user.permissions & 8:
            # 可以创建超级管理员，可设置管理员拥有的权限
            return render_template('admin/register_ad1.html')
        elif current_user.permissions & 4:
            # 可以创建普通管理员，没有权限的管理员
            return render_template('admin/register_ad2.html')
        else:
            return render_template('common/noPermission.html')
    else:
        return render_template('common/nocan.html', u=current_user.username)


@admin.route('/login_ad/', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        ad = User.query.filter(User.username == request.form.get('adname')).first()
        if not ad:
            flash('请输入正确的用户名')
        elif not ad.check_password(request.form.get('passwd')):
            flash('密码有误，请输入正确的密码...')
        else:
            # 修改登录时间
            ad.lastLogin = datetime.now()
            ad.save()
            login_user(ad, remember=True)  # 使用第三方扩展库处理登录状态的维持
            return redirect(url_for('admin.main_page'))
    return render_template('admin/login_ad.html')


# 用户主页面
@admin.route('/main_page_ad/')
@login_required
def main_page():
    if current_user.status == '管理员':  # 当前用户是管理员，才会渲染下面的模板，否则渲染nocan.html
        return render_template('main/main_admin.html', user=current_user)
    else:
        return render_template('common/nocan.html', u=current_user.username)


# 退出登录
@admin.route('/logout_ad/')
def logout():
    logout_user()  # 清除当前用户所有数据
    return redirect(url_for('main.index'))

App/views/common.py
from flask import Blueprint, request, current_app, render_template
from flask_login import login_required, current_user
import os
from App.models import UserFiles, User, Message

common = Blueprint('common', __name__)


# 注销用户
@common.route('/deluser/', methods=['GET', 'POST'])
@login_required
def deluser():
    if current_user.status == '管理员':
        if not current_user.permissions & 1:
            return '你没有注销其他用户权限'
    u = User.query.filter(User.id == request.form.get('id')).first()
    files = UserFiles.query.filter(UserFiles.uid == u.id)
    for f in files:
        # 删除用户文件的聊天记录
        for ms in Message.query.filter(Message.fid == f.id):
            ms.my_del()
        # 删除用户稿件
        if f.my_del():
            delFilePath = current_app.config['UPLOADED_FILES_DEST']
            os.remove(os.path.join(delFilePath, f.fileNewName))
    deliconPath = current_app.config['UPLOADED_PHOTOS_DEST']
    # 删除之前上传过的图片
    if u.icon != 'default.jpg':  # 如果不等于 证明之前有上传过头像 否则就是没有上传过新头像
        os.remove(os.path.join(deliconPath, u.icon))
        os.remove(os.path.join(deliconPath, 'm_' + u.icon))
        os.remove(os.path.join(deliconPath, 's_' + u.icon))
    if u.my_del():
        return '注销成功'
    else:
        return '注销失败'


# 合作伙伴
@common.route('/a-hzhb/', methods=['GET', 'POST'])
@login_required
def hzhb():
    return render_template('common/a-hzhb.html')


# 常见问题
@common.route('/a-cjwt/', methods=['GET', 'POST'])
@login_required
def cjwt():
    return render_template('common/a-cjwt.html')


# 使用教程-用户
@common.route('/a-syjc1/', methods=['GET', 'POST'])
@login_required
def syjc1():
    return render_template('common/a-syjc1.html')


# 使用教程-专家
@common.route('/a-syjc2/', methods=['GET', 'POST'])
@login_required
def syjc2():
    return render_template('common/a-syjc2.html')

App/views/expert.py
from datetime import datetime
from flask import Blueprint, render_template, flash, redirect, url_for
from flask_login import login_user, logout_user, login_required, current_user
from App.forms import Register, Login  # 导入表单注册类
from App.models import User  # User 模型类

expert = Blueprint('expert', __name__)

"""
# 注册步骤
1. 创建模型类
2. 加载flask-migrate扩展库（迁移）
3. 在视图函数中导入模型类
4. 验证用户名是否存在
5. 获取模板前台传递过来的数据
6. 存储
7. 明文密码变成密文密码（加密存储）
8. 消息闪现（注册成功，前去激活...）
"""


@expert.route('/register_ex/', methods=['GET', 'POST'])
def register():
    # 实例化注册表单类
    form = Register()
    # 实例化存储注册表单数据
    e = User()
    if form.validate_on_submit():
        e.username = form.username.data
        e.password = form.userpass.data
        e.email = form.email.data
        e.registerTime = datetime.now()
        e.status = '专家'
        if e.save():
            flash('注册成功，已为您跳转到登录页面...')
        return redirect(url_for('expert.login'))
    return render_template('expert/register.html', form=form)


@expert.route('/login_ex/', methods=['GET', 'POST'])
def login():
    form = Login()
    if form.validate_on_submit():
        u = User.query.filter(User.username == form.username.data).first()
        if not u:
            flash('请输入正确的用户名')
        elif not u.check_password(form.userpass.data):
            flash('密码有误，请输入正确的密码...')
        elif u.status != '专家':
            flash('您不是专家哦~')
        else:
            # 修改登录时间
            u.lastLogin = datetime.now()
            u.save()
            login_user(u, remember=form.remember.data)  # 使用第三方扩展库处理登录状态的维持
            return redirect(url_for('expert.main_page'))
    return render_template('expert/login.html', form=form)


# 专家主页面
@expert.route('/main_page_ex/')
@login_required
def main_page():
    if current_user.status == '专家':  # 当前用户是专家，才会渲染下面的模板，否则渲染nocan.html
        u = current_user
        return render_template('main/main_expert.html', user=u)
    else:
        return render_template('common/nocan.html', u=current_user.username)


# 退出登录
@expert.route('/logout_ex/')
def logout():
    logout_user()  # 清除当前用户所有数据
    return redirect(url_for('main.index'))

App/views/main.py
from flask import Blueprint,render_template

main = Blueprint('main', __name__)


# 首页视图
@main.route('/')
@main.route('/index/')
def index():
    return render_template('main/index.html')

App/views/user.py
from datetime import datetime
from flask import Blueprint, render_template, flash, redirect, url_for
from flask_login import login_user, logout_user, login_required, current_user
from App.forms import Register, Login  # 导入表单注册类
from App.models import User  # User 模型类

user = Blueprint('user', __name__)

"""
# 注册步骤
1. 创建模型类
2. 加载flask-migrate扩展库（迁移）
3. 在视图函数中导入模型类
4. 验证用户名是否存在
5. 获取模板前台传递过来的数据
6. 存储
7. 明文密码变成密文密码（加密存储）
8. 消息闪现（注册成功，前去激活...）
"""


@user.route('/register/', methods=['GET', 'POST'])
def register():
    # 实例化注册表单类
    form = Register()
    u = User()
    if form.validate_on_submit():
        # 实例化存储注册表单数据
        u.username = form.username.data
        u.password = form.userpass.data
        u.email = form.email.data
        u.registerTime = datetime.now()
        u.status = '作者'
        u.save()
        flash('注册成功，以为您跳转到登录页面...')
        return redirect(url_for('user.login'))
    return render_template('user/register.html', form=form)


@user.route('/login/', methods=['GET', 'POST'])
def login():
    form = Login()
    if form.validate_on_submit():
        u = User.query.filter(User.username == form.username.data).first()
        if not u:
            flash('请输入正确的用户名')
        elif not u.check_password(form.userpass.data):
            flash('密码有误，请输入正确的密码...')
        elif u.status != '作者':
            flash('您不是投稿的作者哦~')
        else:
            # 修改登录时间
            u.lastLogin = datetime.now()
            u.save()
            login_user(u, remember=form.remember.data)  # 使用第三方扩展库处理登录状态的维持
            return redirect(url_for('user.main_page'))
    return render_template('user/login.html', form=form)


# 用户主页面
@user.route('/main_page/')
@login_required
def main_page():
    if current_user.status == '作者':  # 当前用户是作者，才会渲染下面的模板，否则渲染nocan.html
        u = current_user
        return render_template('main/main_user.html', user=u)
    else:
        return render_template('common/nocan.html', u=current_user.username)


# 退出登录
@user.route('/logout/')
def logout():
    logout_user()  # 清除当前用户所有数据
    return redirect(url_for('main.index'))

App/templates/main/main_expert.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>在线投稿与稿件管理系统-专家界面</title>
    <link rel="stylesheet" href="../../static/dist/css/bootstrap.css">
    <style>
        * {
            margin: 0;
            padding: 0;
        }

        .icon_my {
            height: 32px;
            width: 32px;
            margin: 8px 0 8px 30px;
            border: 1px solid #666;
            border-radius: 5px;
        }

        .nav .icon_a {
            width: 32px;
            height: 32px;
            position: absolute;
            right: 0;
            top: 8px;
            float: left
        }

        .username {
            color: #ddd;
            font-size: 16px;
            margin-right: 20px;
            line-height: 50px;
        }

        .my_body {
            background: url("../../static/img/my_body.jpg") no-repeat fixed center/100% 100%;


        }

        .father {
            width: 1200px;
            margin: 0 auto;

        }

        .father div {
            border-radius: 4px;
        }

        .son1 {
            text-align: center;
            width: 100%;
            height: 150px;
            padding-top: 35px;
            color: dodgerblue;
            background-color: rgba(200, 200, 200, 0.4);
        }

        .son1 h1 {
            font-family: '华文行楷';
            font-weight: 500;
            font-size: 50px;
            line-height: 1.1;
            margin-bottom: 10px;
        }

        .son2 {
            height: 720px;
            margin-top: 10px;
        }

        .son2 .left {
            float: left;
            width: 150px;
            height: 100%;
            background-color: rgba(200, 200, 200, 0.4);
            text-align: center;
            padding-top: 20px;
        }

        .son2 .left .my_btn {
            width: 100px;
            height: 30px;
            margin: 10px auto;
            border-radius: 4px;
            background-color: #ddd;
            position: relative;
            border: 1px solid blue;
            font-size: 13px;
        }

        .son2 .left .my_btn a {
            width: 100%;
            height: 100%;
            line-height: 40px;
            color: #000;
            position: absolute;
            top: 0;
            left: 0;
        }

        .son2 .right {
            float: right;
            width: 1040px;
            height: 100%;
            background-color: rgba(200, 200, 200, 0.4);
        }

        .son2 .right .iframe {
            width: 100%;
            height: 100%;
            scroll-behavior: auto;
            border-radius: 4px;
            background: url("../../static/img/q04.jpg") no-repeat center/100% 100%;
            opacity: 0.8;
        }

        .blank {
            width: 100%;
            height: 50px;
            margin-top: 10px;
            background-color: rgba(200, 200, 200, 0.4);
            text-align: center;
            position: relative;
        }

        .blank_son {
            height: 40px;
            text-align: center;
            padding: 5px 0;
        }

        .blank_son ul {
            list-style: none;
        }

        .blank_son li a {
            color: #1cf;
            float: left;
            font-size: 15px;
            padding: 0 20px;
            text-decoration: none;
            line-height: 40px;
            border-left: 1px solid #999;
        }

        .blank_son li:first-child a {
            border: 0;
            margin-left: 30px;
        }

        .son3 {
            width: 100%;
            margin-top: 10px;
            text-align: center;
            padding: 20px;
            background-color: rgba(200, 200, 200, 0.4);
            color: #222;
        }

        .son3_1 {
            width: 500px;
            text-align: center;
            margin: auto;
        }

        .son3_1 a {
            color: #222;
            padding: 2px 10px;
            border-left: 1px solid #555;
            line-height: 15px;

        }

        .son3_1 a:first-child {
            border: 0;
        }

        .son_bottom {
            width: 100%;
            height: 36px;
            margin-top: 10px;
            background-color: rgba(200, 200, 200, 0.4);
            text-align: center;
            line-height: 36px;
            color: #222;
        }
    </style>
    <script src="../../static/js/jquery-1.12.4.js"></script>
</head>
<body>
<div class="my_body">
    <div class="my_nav">
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand" href="#">
                        <span class="glyphicon glyphicon-fire .sr-only"></span>
                    </a>
                </div>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="{{ url_for('expert.main_page',_external=True) }}">首页</a></li>
                        <li><a href="#">专家界面</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <img src="{{ url_for('static',filename='upload/icon/s_'+user.icon) }}" alt="还没有上传图片哦~"
                                 class="icon_my">
                            <a href="{{ url_for('expertcenter.upload') }}" target="_blank" class="icon_a"></a>
                        </li>
                        <li class="username"><a href="{{ url_for('expertcenter.expert_info') }}"
                                                target="_blank">{{ user.username }}</a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-haspopup="true"
                               aria-expanded="false">个人中心<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="{{ url_for('expertcenter.expert_info') }}" target="_blank">基本信息</a></li>
                                <li><a href="{{ url_for('expertcenter.upload') }}" target="_blank">更换头像</a></li>
                                <li><a href="{{ url_for('expertcenter.alterPasswd') }}" target="_blank">修改密码</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="#" id="deluser">注销当前用户</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="{{ url_for('expert.logout') }}">退出登录</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>
    <div class="father">
        <div class="son1">
            <h1>专家审稿管理系统</h1>
        </div>
        <div class="blank">
            <div class="blank_son">
                <ul>
                    <li><a href="{{ url_for('expertcenter.expert_info') }}" target="_blank">基本信息</a></li>
                    <li><a href="{{ url_for('expertcenter.showFiles') }}" target="_blank">待审稿件</a></li>
                    <li><a href="{{ url_for('expertcenter.showPass') }}" target="_blank">已审稿件</a></li>
                    <li><a href="{{ url_for('expertcenter.allFiles') }}" target="_blank">所有稿件</a></li>
                </ul>
            </div>

        </div>
        <div class="son2">
            <div class="left">

                <button class="my_btn">
                    基本信息
                    <a href="{{ url_for('expertcenter.expert_info') }}" target="my_right"></a>
                </button>
                <br>


                <button class="my_btn">
                    待审稿件
                    <a href="{{ url_for('expertcenter.showFiles') }}" target="my_right"></a>
                </button>
                <br>


                <button class="my_btn">
                    已审稿件
                    <a href="{{ url_for('expertcenter.showPass') }}" target="my_right"></a>
                </button>
                <br>

                <button class="my_btn">
                    所有稿件
                    <a href="{{ url_for('expertcenter.allFiles') }}" target="my_right"></a>
                </button>
                <br>


                <button class="my_btn">
                    更换头像
                    <a href="{{ url_for('expertcenter.upload') }}" target="my_right"></a>
                </button>
                <br>

                <button class="my_btn">
                    修改密码
                    <a href="{{ url_for('expertcenter.alterPasswd') }}" target="my_right"></a>
                </button>
                <br>

            </div>
            <div class="right">
                <iframe frameborder="0" name="my_right" class="iframe">
                </iframe>
            </div>
        </div>

        <div class="son3">
            <div class="son3_1">
                <p>
                    友情链接：
                    <a href="{{ url_for('common.hzhb') }}" target="_blank">合作伙伴</a>
                    <a href="{{ url_for('common.syjc2') }}" target="_blank">使用教程</a>
                    <a href="{{ url_for('common.cjwt') }}" target="_blank">常见问题</a>
                </p>
                <p>咨询热线/微信：18898689655、13794586264</p>
                <p>客服QQ:1258649537、5698564853、6354896586</p>
                <p>【版权所有】北京光影文化传播有限公司</p>
                <p>地址：北京市海淀区科学院南路3号光影大厦12楼C08室</p>
            </div>
        </div>

        <div class="son_bottom">
            <p>BJ-ZXTG-E-2020</p>
        </div>
    </div>
</div>
<script>
    $('#deluser').click(function () {
        let x;
        x = confirm('确定要注销账户吗？');
        console.log(x);
        if (x) {
            $.post({
                url: '/deluser/',
                data: {id: '{{user.id}}', deluser: x},
                complete: function () {
                    console.log('请求完成了');
                },
                success: function (data) {
                    console.log(data);
                    alert(data);
                    console.log('请求成功了');
                    {# 刷新页面 #}
                    location.reload();

                },
                error: function (err) {
                    alert(err);
                    console.log('出错了');
                    console.log(err);
                }
            });
        }
    });
</script>
<script src="../../static/dist/js/bootstrap.js"></script>
</body>
</html>

App/templates/main/main_user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>在线投稿与稿件管理系统</title>
    <link rel="stylesheet" href="../../static/dist/css/bootstrap.css">
    <style>
        * {
            margin: 0;
            padding: 0;
        }

        .icon_my {
            height: 32px;
            width: 32px;
            margin: 8px 0 8px 30px;
            border: 1px solid #666;
            border-radius: 5px;
        }

        .nav .icon_a {
            width: 32px;
            height: 32px;
            position: absolute;
            right: 0;
            top: 8px;
            float: left
        }

        .username {
            color: #ddd;
            font-size: 16px;
            margin-right: 20px;
            line-height: 50px;
        }

        .my_body {
            background: url("../../static/img/my_body.jpg") no-repeat fixed center/100% 100%;


        }

        .father {
            width: 1200px;
            margin: 0 auto;

        }

        .father div {
            border-radius: 4px;
        }

        .son1 {
            text-align: center;
            width: 100%;
            height: 150px;
            padding-top: 35px;
            color: dodgerblue;
            background-color: rgba(200, 200, 200, 0.4);
        }

        .son1 h1 {
            font-family: '华文行楷';
            font-weight: 500;
            font-size: 50px;
            line-height: 1.1;
            margin-bottom: 10px;
        }

        .son2 {
            height: 720px;
            margin-top: 10px;
        }

        .son2 .left {
            float: left;
            width: 150px;
            height: 100%;
            background-color: rgba(200, 200, 200, 0.4);
            text-align: center;
            padding-top: 20px;
        }

        .son2 .left .my_btn {
            width: 100px;
            height: 30px;
            margin: 10px auto;
            border-radius: 4px;
            background-color: #ddd;
            position: relative;
            border: 1px solid blue;
            font-size: 13px;
        }

        .son2 .left .my_btn a {
            width: 100%;
            height: 100%;
            line-height: 40px;
            color: #000;
            position: absolute;
            top: 0;
            left: 0;
        }

        .son2 .right {
            float: right;
            width: 1040px;
            height: 100%;
            background-color: rgba(200, 200, 200, 0.4);
        }

        .son2 .right .iframe {
            width: 100%;
            height: 100%;
            scroll-behavior: auto;
            border-radius: 4px;
            background: url("../../static/img/q04.jpg") no-repeat center/100% 100%;
            opacity: 0.8;
        }

        .blank {
            width: 100%;
            height: 50px;
            margin-top: 10px;
            background-color: rgba(200, 200, 200, 0.4);
            text-align: center;
            position: relative;
        }

        .blank_son {
            height: 40px;
            text-align: center;
            padding: 5px 0;
        }

        .blank_son ul {
            list-style: none;
        }

        .blank_son li a {
            color: #1cf;
            float: left;
            font-size: 15px;
            padding: 0 20px;
            text-decoration: none;
            line-height: 40px;
            border-left: 1px solid #999;
        }

        .blank_son li:first-child a {
            border: 0;
            margin-left: 30px;
        }

        .son3 {
            width: 100%;
            margin-top: 10px;
            text-align: center;
            padding: 20px;
            background-color: rgba(200, 200, 200, 0.4);
            color: #222;
        }

        .son3_1 {
            width: 500px;
            text-align: center;
            margin: auto;
        }

        .son3_1 a {
            color: #222;
            padding: 2px 10px;
            border-left: 1px solid #555;
            line-height: 15px;

        }

        .son3_1 a:first-child {
            border: 0;
        }

        .son_bottom {
            width: 100%;
            height: 36px;
            margin-top: 10px;
            background-color: rgba(200, 200, 200, 0.4);
            text-align: center;
            line-height: 36px;
            color: #222;
        }
    </style>
    <script src="../../static/js/jquery-1.12.4.js"></script>
</head>
<body>
<div class="my_body">
    <div class="my_nav">
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand" href="#">
                        <span class="glyphicon glyphicon-fire .sr-only"></span>
                    </a>
                </div>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="{{ url_for('user.main_page',_external=True) }}">首页</a></li>
                        <li><a href="#">用户投稿及稿件处理界面</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <img src="{{ url_for('static',filename='upload/icon/s_'+user.icon) }}" alt="还没有上传图片哦~"
                                 class="icon_my">
                            <a href="{{ url_for('owncenter.upload') }}" target="_blank" class="icon_a"></a>
                        </li>
                        <li class="username"><a href="{{ url_for('owncenter.user_info') }}"
                                                target="_blank">{{ user.username }}</a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-haspopup="true"
                               aria-expanded="false">个人中心<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="{{ url_for('owncenter.user_info') }}" target="_blank">基本信息</a></li>
                                <li><a href="{{ url_for('owncenter.upload') }}" target="_blank">更换头像</a></li>
                                <li><a href="{{ url_for('owncenter.alterPasswd') }}" target="_blank">修改密码</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="#" id="deluser">注销当前用户</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="{{ url_for('user.logout') }}">退出登录</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>
    <div class="father">
        <div class="son1">
            <h1>在线投稿与稿件管理系统</h1>
        </div>
        <div class="blank">
            <div class="blank_son">
                <ul>
                    <li><a href="{{ url_for('owncenter.user_info') }}" target="_blank">基本信息</a></li>
                    <li><a href="{{ url_for('owncenter.upload_files') }}" target="_blank">我要投稿</a></li>
                    <li><a href="{{ url_for('owncenter.showFiles') }}" target="_blank">已投稿件</a></li>
                    <li><a href="{{ url_for('owncenter.showPass') }}" target="_blank">稿件反馈</a></li>
                </ul>
            </div>

        </div>
        <div class="son2">
            <div class="left">

                <button class="my_btn">
                    基本信息
                    <a href="{{ url_for('owncenter.user_info') }}" target="my_right"></a>
                </button>
                <br>


                <button class="my_btn">
                    我要投稿
                    <a href="{{ url_for('owncenter.upload_files') }}" target="my_right"></a>
                </button>
                <br>

                <button class="my_btn">
                    已投稿件
                    <a href="{{ url_for('owncenter.showFiles') }}" target="my_right"></a>
                </button>
                <br>


                <button class="my_btn">
                    审稿反馈
                    <a href="{{ url_for('owncenter.showPass') }}" target="my_right"></a>
                </button>
                <br>

                <button class="my_btn">
                    更换头像
                    <a href="{{ url_for('owncenter.upload') }}" target="my_right"></a>
                </button>
                <br>

                <button class="my_btn">
                    修改密码
                    <a href="{{ url_for('owncenter.alterPasswd') }}" target="my_right"></a>
                </button>
                <br>


            </div>
            <div class="right">
                <iframe frameborder="0" name="my_right" class="iframe">
                </iframe>
            </div>
        </div>

        <div class="son3">
            <div class="son3_1">
                <p>
                    友情链接：
                    <a href="{{ url_for('common.hzhb') }}" target="_blank">合作伙伴</a>
                    <a href="{{ url_for('common.syjc1') }}" target="_blank">使用教程</a>
                    <a href="{{ url_for('common.cjwt') }}" target="_blank">常见问题</a>
                </p>
                <p>咨询热线/微信：18898689655、13794586264</p>
                <p>客服QQ:1258649537、5698564853、6354896586</p>
                <p>【版权所有】北京光影文化传播有限公司</p>
                <p>地址：北京市海淀区科学院南路3号光影大厦12楼C08室</p>
            </div>
        </div>

        <div class="son_bottom">
            <p>BJ-ZXTG-U-2020</p>
        </div>
    </div>
</div>
<script>
    $('#deluser').click(function () {
        let x;
        x = confirm('确定要注销账户吗？');
        console.log(x);
        if (x) {
            $.post({
                url: '/deluser/',
                data: {id: '{{user.id}}', deluser: x},
                complete: function () {
                    console.log('请求完成了');
                },
                success: function (data) {
                    console.log(data);
                    alert(data);
                    console.log('请求成功了');
                    {# 刷新页面 #}
                    location.reload();

                },
                error: function (err) {
                    alert(err);
                    console.log('出错了');
                    console.log(err);
                }
            });
        }
    });
</script>
<script src="../../static/dist/js/bootstrap.js"></script>
</body>
</html>